server:
  port: 3030
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/security-sample?charSet=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A58611111111118782F413F4428472B4B6250000000000B5970
      expiration: 600000 # 10 minutes
